### ISSUE TITLE
Some additional work to make it even better

### ISSUE THREAD

**Issue by ddutt** [mweisel/cisco-nxos9kv-vagrant-libvirt#1]
Hi Marc,

Thanks a ton for doing this work. Its so helpful, I can't begin to tell you. I'll be pointing others to this link. 

Couple of suggestions:
1. I got a 9.3.4 image and it got stuck at the "loader >" prompt. I had to modify your expect script to handle this.
2. Add modifying the version at the head of your expect scripts to the README.
3. Add the following file to your repo and directly add the Vagrant box via this method. "vagrant box add nxos.json" This allows people to keep multiple versions in a clean way.

`{
  "name": "cisco/nxos",
  "description": "Cisco NXOSv",
  "versions": [
    {
      "version": "9.3.4",
      "providers": [
        {
          "name": "libvirt",
          "url": "file:///home/dinesh/work/cisco-nxos9kv-vagrant-libvirt/cisco-nxosv.box"
        }
      ]
    }
  ]
}
`

**Comment by mweisel** [comment]
Dinesh,

I appreciate the feedback. I would like to mention I really enjoyed **Cloud Native Data Center Networking**. I wholeheartedly agree when you stated _Vagrant is one of the most useful tools in the modern sysadmin toolkit_. As we know, the Vagrant workflow is also ideal for network automation labs and testing.

**Comment by sh0x** [comment]
Thanks a ton for sharing this!! 

I hit the loader prompt too and added this below the spawn statement in `cisco_nexus9x00v_base_conf.exp`.

```
# loader prompt
expect "loader >"
send "boot nxos.$nxos.bin\r"
```

```
No autoboot or failed autoboot. falling to loader

                Loader Version 5.9

loader > boot nxos.9.3.5.bin
Booting nxos.9.3.5.bin
Trying diskboot
 Filesystem type is ext2fs, partition type 0x83
Image valid
...
```

[Troubleshooting the Cisco Nexus 9000v - Common Issues for All Hypervisors](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/nx-osv-93-95/configuration/guide/cisco-nexus-9000v-9300v-9500v-guide-93x/m-troubleshooting-the-cisco-nexus-9000v-93x.html#Cisco_Reference.dita_1beffe24-20b8-4d6f-ab55-2388277d1d18)
