### ISSUE TITLE
Ansible version requirements

### ISSUE THREAD

**Issue by networkop** [mweisel/cisco-nxos9kv-vagrant-libvirt#2]
Hi Marc,
I've also hit a similar issue as Dinesh with the latest 9.3.4 image, I had to add the following to the top of `files/cisco_nexus9x00v_base_conf.exp`
```
expect "loader >"
send "boot nxos.9.3.4.bin\r"
```
However, the main issue was that ansible's `script` module has changed somewhere between [2.5](https://docs.ansible.com/ansible/2.5/plugins/inventory/script.html?highlight=script) and [2.7](https://docs.ansible.com/ansible/2.7/modules/script_module.html) and I was getting an error in `set the cisco nxos base configuration` task. So I thought it'd be nice to add that Ansible must be `>= 2.7` somewhere in readme.

**Comment by ddutt** [comment]
Yes, thats the problem I ran into as well.

**Comment by mweisel** [comment]
Updated README.
