### ISSUE TITLE
MAC address issue

### ISSUE THREAD

**Issue by ddutt** [mweisel/cisco-nxos9kv-vagrant-libvirt#3]
Hi Marc,

With 9.3.4, I face another strange issue, that's seemingly caused by the use of the MAC address of the interface being in the OUI 52:54:00. I cannot ping the IP address of the other end of a p2p routed link. Have you run into something similar? What i see is the "Source MAC address is our own" count going up in "show ip arp statistics". With ethanalyzer, I see the ARP packet come, but no reply ever go out. Once I change the MAC addresses on the interface to be from a different OUI, it just works.

**Comment by networkop** [comment]
I think this is due to the U/L bit of the MAC address. I've seen this previously in some other vendor's virtual switch, where dataplane won't forward packets with U/L bit set to L and would work perfectly fine when it's set to U. 
But is this something that's possible to set up during the initial build and keep it fixed forever? Usually changing the MAC of the management interface will force all other MACs to use that as a base but this is done at runtime and not buildtime.

**Comment by ddutt** [comment]
@networkop : I don't know if it can be setup during the build time. I have to see how it can be changed during runtime. Trying to assign MACs to all interfaces is a pain.

**Comment by ddutt** [comment]
@networkop: I misunderstood you. I'll see if I can build a version with the MAC address modified.

**Comment by networkop** [comment]
@ddutt: one potential problem I see with modifying it at build time (in expect script) is that all boxes will have the same base mac which may result in similar macs assigned different virtual switches. But if you manage to make it work (by randomizing it somehow), please let us know.

**Comment by ddutt** [comment]
@networkop: Thats why I deleted my comment :) I couldn't think of a simple way off the bat. Its funny though that this problem exists only with NXOS. JunOS, Arista and of course Cumulus, don't have this problem.

**Comment by ddutt** [comment]
@mweisel, @networkop : We can close this out. Add the line management_mac_address to the node config in Vagrantfile like this:
   ```
 device.vm.provider :libvirt do |v|
       v.memory = 6144
        v.management_network_mac = "44:39:39:00:00:01"
    end
```
 And all the other interfaces change their MAC address appropriately. For example, with the MAC address shown above, you get Eth1/1's mac as 4400.0001.0101, Eth1/2's MAC as 4400.0001.0102 and so on.
