### ISSUE TITLE
DHCP on the mgmt MAC has trouble due to client ID

### ISSUE THREAD

**Issue by ddutt** [mweisel/cisco-nxos9kv-vagrant-libvirt#4]
Hi,
I also seem to have difficulty with spinning up multiple NXOS nodes. They all send the same client-id and so libvirt's DHCP server (dnsmasq) does not assign separate IP addresses to each node. I had it working a while back using the dhcp-host=52:54:00:*:*:*,id:* option with dnsmasq's configuration, but thats not working after the reboot :(

Any suggestions on this?

Dinesh

**Comment by mweisel** [comment]
I ran into the same issue. The following combination has made it more manageable:

* [Controlling Vagrant Box Management IP](https://codingpackets.com/blog/controlling-vagrant-box-management-ip)
* Disabling parallelism with `vagrant up --no-parallel`

I created a sample project to demonstrate what has worked best for me - [cisco-nexus-ospf-p2p](https://github.com/mweisel/cisco-nexus-ospf-p2p)
